# Source: https://js.langchain.com/docs/integrations/vectorstores/pgvector/
version: "3"
services:
  db:
    hostname: 127.0.0.1
    image: pgvector/pgvector:pg17
    ports:
      - 5432:5432
    # restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
