# Source: https://js.langchain.com/docs/integrations/vectorstores/pgvector/
services:
  pgvector:
    hostname: 127.0.0.1
    image: pgvector/pgvector:pg17
    ports:
      - 5433:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=civilcode
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - civilcode_pgvector:/var/lib/postgresql/data
  
  psql:
    image: postgres:17.2-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=civilcode
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - civilcode_psql:/var/lib/postgresql/data

volumes:
  civilcode_pgvector:
  civilcode_psql:
